use parsentry_core::Language;
use serde::{Deserialize, Serialize};

/// A tree-sitter query generated by the threat model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatQuery {
    /// PAR classification: "principal", "action", or "resource"
    pub par_type: String,
    /// "definition" or "reference"
    pub query_type: String,
    /// Tree-sitter S-expression query
    pub query: String,
    /// Human-readable description of what this query detects
    pub description: String,
}

/// A single threat identified in the repository.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatEntry {
    /// Unique identifier (e.g. "THREAT-001")
    pub id: String,
    /// Threat category (e.g. "SQL Injection", "Command Injection")
    pub category: String,
    /// Why this threat applies to this repository
    pub rationale: String,
    /// MITRE ATT&CK technique IDs
    pub attack_vectors: Vec<String>,
    /// Glob patterns for files likely affected (e.g. "src/db/**", "api/")
    pub attack_surface: Vec<String>,
    /// Target language for the queries
    pub language: Language,
    /// Tree-sitter queries to detect this threat
    pub queries: Vec<ThreatQuery>,
}

/// Complete threat model for a repository.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatModel {
    /// Repository identifier (path or owner/repo)
    pub repository: String,
    /// ISO-8601 timestamp of generation
    pub generated_at: String,
    /// High-level summary of the repository's security posture
    pub summary: String,
    /// Identified threats with detection queries
    pub threats: Vec<ThreatEntry>,
}

impl ThreatModel {
    /// Collect all queries grouped by language (cloned for thread safety).
    pub fn queries_by_language(&self) -> std::collections::HashMap<Language, Vec<ThreatQuery>> {
        let mut map: std::collections::HashMap<Language, Vec<ThreatQuery>> =
            std::collections::HashMap::new();
        for threat in &self.threats {
            map.entry(threat.language)
                .or_default()
                .extend(threat.queries.clone());
        }
        map
    }

    /// Total number of generated queries.
    pub fn total_queries(&self) -> usize {
        self.threats.iter().map(|t| t.queries.len()).sum()
    }
}
